/**
 * Datos de muestra para previsualizar el diseño mientras D1 está vacío.
 * Estos datos NO se usan en producción; son reemplazados al cargar el seed real.
 */

export const sampleOccasions = [
  { name: "Cumpleaños", slug: "cumpleanos", icon: "🎂", to: "/ocasion/cumpleanos" },
  { name: "Baby shower", slug: "baby-shower", icon: "🍼", to: "/ocasion/baby-shower" },
  { name: "Quinceaños", slug: "quinceanos", icon: "👑", to: "/ocasion/quinceanos" },
  { name: "Bautizos y comuniones", slug: "bautizos", icon: "✝️", to: "/ocasion/bautizos" },
];

export const sampleProducts = [
  {
    id: 1,
    name: "Morral temático Safari",
    slug: "morral-tematico-safari",
    code: "MAR-SAF-01",
    categoryId: 1,
    shortDesc: "Morral de lona con estampado safari, ideal para cumpleaños infantiles.",
    longDesc: "",
    price: 12000,
    priceType: "desde" as const,
    minQty: 25,
    material: "Lona",
    colors: null,
    dimensions: "30x25x10 cm",
    weight: "180 g",
    leadTime: "5-7 días",
    customization: "Bordado de nombre",
    active: true,
    featured: true,
    featuredOrder: 1,
    seoTitle: null,
    seoDesc: null,
    ogImageKey: null,
    createdAt: 0,
    updatedAt: 0,
    images: [],
  },
  {
    id: 2,
    name: "Lonchera personalizada",
    slug: "lonchera-personalizada",
    code: "LON-PER-02",
    categoryId: 2,
    shortDesc: "Lonchera térmica con nombre y temática del evento.",
    longDesc: "",
    price: 8500,
    priceType: "desde" as const,
    minQty: 30,
    material: "Neopreno",
    colors: null,
    dimensions: "22x18x8 cm",
    weight: "120 g",
    leadTime: "4-6 días",
    customization: "Estampado full color",
    active: true,
    featured: true,
    featuredOrder: 2,
    seoTitle: null,
    seoDesc: null,
    ogImageKey: null,
    createdAt: 0,
    updatedAt: 0,
    images: [],
  },
  {
    id: 3,
    name: "Kit baby shower 10 piezas",
    slug: "kit-baby-shower-10",
    code: "KIT-BSH-03",
    categoryId: 6,
    shortDesc: "Kit completo: morral, gorrito, babero y más para baby shower.",
    longDesc: "",
    price: 35000,
    priceType: "unitario" as const,
    minQty: 10,
    material: "Algodón / Lona",
    colors: null,
    dimensions: "Variado",
    weight: "650 g",
    leadTime: "7-10 días",
    customization: "Personalización completa por temática",
    active: true,
    featured: true,
    featuredOrder: 3,
    seoTitle: null,
    seoDesc: null,
    ogImageKey: null,
    createdAt: 0,
    updatedAt: 0,
    images: [],
  },
  {
    id: 4,
    name: "Caja recordatorio premium",
    slug: "caja-recordatorio-premium",
    code: "REC-CAJ-04",
    categoryId: 6,
    shortDesc: "Caja decorativa con dulces y etiqueta personalizada.",
    longDesc: "",
    price: 6500,
    priceType: "desde" as const,
    minQty: 50,
    material: "Cartón / Tela",
    colors: null,
    dimensions: "12x12x6 cm",
    weight: "90 g",
    leadTime: "3-5 días",
    customization: "Etiqueta personalizada",
    active: true,
    featured: true,
    featuredOrder: 4,
    seoTitle: null,
    seoDesc: null,
    ogImageKey: null,
    createdAt: 0,
    updatedAt: 0,
    images: [],
  },
  {
    id: 5,
    name: "Tula para quinceaños",
    slug: "tula-quinceanos",
    code: "TUL-QUI-05",
    categoryId: 3,
    shortDesc: "Tula elegante con nombre bordado para celebrar los 15.",
    longDesc: "",
    price: 28000,
    priceType: "desde" as const,
    minQty: 20,
    material: "Lona premium",
    colors: null,
    dimensions: "40x35 cm",
    weight: "300 g",
    leadTime: "7-10 días",
    customization: "Bordado + color a elección",
    active: true,
    featured: false,
    featuredOrder: 0,
    seoTitle: null,
    seoDesc: null,
    ogImageKey: null,
    createdAt: 0,
    updatedAt: 0,
    images: [],
  },
  {
    id: 6,
    name: "Cangurera temática",
    slug: "cangurera-tematica",
    code: "CAN-TEM-06",
    categoryId: 4,
    shortDesc: "Cangurera pequeña con diseño para repartir en la fiesta.",
    longDesc: "",
    price: 5500,
    priceType: "desde" as const,
    minQty: 40,
    material: "Lona",
    colors: null,
    dimensions: "20x14 cm",
    weight: "80 g",
    leadTime: "3-5 días",
    customization: "Estampado",
    active: true,
    featured: false,
    featuredOrder: 0,
    seoTitle: null,
    seoDesc: null,
    ogImageKey: null,
    createdAt: 0,
    updatedAt: 0,
    images: [],
  },
];
